version: '3'
services:
  library-syncer-server:
    container_name: clr-server
    restart: unless-stopped
    image: ghcr.io/jbowdre/clr-server:latest
    environment:
      - TZ=UTC
      - SYNCER_UID=31337
    ports:
      - "2222:22"
    volumes:
      - './data/ssh:/home/syncer/.ssh'
      - './data/library:/syncer/library'
